### ISSUE TITLE
Parsing error: Cannot read file tsconfig.json

### ISSUE THREAD

**Issue by tinchoz49** [Raynos/tsdocstandard#4]
Hi @Raynos how are you?

I was playing with your project a while, it's really awesome.

Something that I notice is that if you started a clean project and you forgot the first time to add the tsconfig.json the `tsdocstandard` says that cannot read tsconfig.json and it makes sense but then if you add the file tsdocstandard keep reporting the same error.

I don't if this could be related to your project or typescript-eslint.

Reproduce steps:

```
$ mkdir newproject
$ cd newproject
$ npm install -D typescript tsdocstandard
$ npx tsdocstandard
```

Then add a tsconfig.json and run again: `npx tsdocstandard`

**Comment by Raynos** [comment]
Let me try this and see what's happening.

**Comment by Raynos** [comment]
I always run `tsc && tsdocstandard` ; aka run the typescript compiler for typescript errors before I run the linter.

This can helpc atch issues.

**Comment by Raynos** [comment]
```sh
raynos at raynos-Precision-5530  
~/projects/foobar
$ tsc 
error TS18003: No inputs were found in config file '/home/raynos/projects/foobar/tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '[]'.


Found 1 error.

raynos at raynos-Precision-5530  
~/projects/foobar
$ tsdocstandard
tsdocstandard: JavaScript + Typescript + JSDoc (https://github.com/Raynos/tsdocstandard)
  /home/raynos/projects/foobar/index.js:0:0: Parsing error: Cannot read file '/home/raynos/projects/foobar/tsconfig.json'.
```

The tsdocstandard error is complaining about `tsconfig.json` but the `tsc` error is better and saying that include / exclude is not correct in tsconfig.json

**Comment by Raynos** [comment]
```
  /home/raynos/projects/foobar/index.js:0:0: Parsing error: Cannot read file '/home/raynos/projects/foobar/tsconfig.json'.
```

Oh; the JSON file generated by `tsc` is not valid JSON. It is JSON5 ( with comments ) ...

**Comment by Raynos** [comment]
I see the same error.

It looks like `standard` or `eslint` has some caching builtin to not "lint" the exact same file twice.

I would recommend added some new lines to your source code. Saving that, and running `tsdocstandard` again.

**Comment by Raynos** [comment]
This is the tsconfig.json I ended up creating in a new temporary project

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "allowJs": true,
    "checkJs": true,
    "noEmit": true,
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```

This is the one I copy around in more serious projects ( https://github.com/Raynos/error/blob/master/tsconfig.json ).

**Comment by tinchoz49** [comment]
Thanks for the quick response. Yes, I was using that tsconfig on my tests, actually I found this project thanks to `error` :smile: 

So the problem was my files to lint beeing cache. Thanks for your help.

Can I ask you two questions more here or should I open another issue for that?

**Comment by Raynos** [comment]
Fixes part of the problem in https://github.com/Raynos/tsdocstandard/pull/5

The part where `eslint` does caching and does not invalidate the cache on a change to `tsconfig.json` is upstream in eslint or eslint typescript

**Comment by Raynos** [comment]
@tinchoz49 open a new issuew ith both questions

**Comment by Raynos** [comment]
Published v15.6.0

**Comment by tinchoz49** [comment]
fixed

**Comment by Raynos** [comment]
> Can I ask you two questions more here or should I open another issue for that?

If you had another question, let me know. I'd love to improve the documentation here.
